### ISSUE TITLE
Allow multiple directories

### ISSUE THREAD

**Issue by chansizzle** [jboucly/MMM-FTP-image#4]
Currently only 1 directory can be used/presented to the screen. Can you look into adding capabilities for multiple directories and for sub-directories please? Trying `magicMirror/*` results in errors.

Perhaps the the capability for an array of directories:
```
dirPathArray: [
               "/magicMirror",
               "/magicMirror/aaa",
               "/magicMirror/bbb",
               "/magicMirror/ccc",
               "/a_different_ftp_directory",
               ],
```

and/or perhaps something like these variables to allow sub-directories:
```
selectFromSubdirectories: true, 
ignoreDirRegex: "a^",
```

Thank you for considering this request!

**Comment by jboucly** [comment]
Hello @chansizzle 
I will try to find a moment to implement this new feature !
If you want to implement it you can propose a PR

**Comment by jboucly** [comment]
Hello @chansizzle 

I'm starting the devs on the implementation of this new feature!
