### ISSUE TITLE
Exception when reaching last image, and trying to load the next

### ISSUE THREAD

**Issue by Theofrastus** [jboucly/MMM-FTP-image#8]
Thanks for this great module! It's one of the centerpieces of my magic mirror setup, and I really appreciate it!

I'm running into the following error:

**Error description:**

When the module reaches the last of the images in the directory, and attempts to load the next, it will stay on the last image indefinitely. Looking at the logs, an exception is thrown.

**Expected behavior:**

The module should loop and start from the first image in the directory again.

**Details:**

Here's the exception:

> 
> 0|mm       | [2024-11-26 09:26:31.888] [ERROR] TypeError: Cannot read properties of undefined (reading 'name')
> 0|mm       |     at Class.dirChangeAlgo (/home/pi/MagicMirror/modules/MMM-FTP-image/node_helper.js:71:72)
> 0|mm       |     at module.exports.<anonymous> (/home/pi/MagicMirror/modules/MMM-FTP-image/node_helper.js:49:11)
> 0|mm       |     at module.exports.emit (node:events:519:28)
> 0|mm       |     at Object.reentry [as cb] (/home/pi/MagicMirror/modules/MMM-FTP-image/node_modules/ftp/lib/connection.js:238:14)
> 0|mm       |     at Parser.<anonymous> (/home/pi/MagicMirror/modules/MMM-FTP-image/node_modules/ftp/lib/connection.js:117:20)
> 0|mm       |     at Parser.emit (node:events:519:28)
> 0|mm       |     at Parser._write (/home/pi/MagicMirror/modules/MMM-FTP-image/node_modules/ftp/lib/parser.js:59:10)
> 0|mm       |     at writeOrBuffer (node:internal/streams/writable:564:12)
> 0|mm       |     at _write (node:internal/streams/writable:493:10)
> 0|mm       |     at Writable.write (node:internal/streams/writable:502:10)
> 0|mm       |     at Socket.ondata (/home/pi/MagicMirror/modules/MMM-FTP-image/node_modules/ftp/lib/connection.js:273:20)
> 0|mm       |     at Socket.emit (node:events:519:28)
> 0|mm       |     at addChunk (node:internal/streams/readable:559:12)
> 0|mm       |     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
> 0|mm       |     at Readable.push (node:internal/streams/readable:390:5)
> 0|mm       |     at TCP.onStreamRead (node:internal/stream_base_commons:191:23)

And here's my config:

>     {
>         module: 'MMM-FTP-image',
>         position: 'middle_center',
>         config: {
>             // FTP server configuration
>             port: 21,
>             user: '<user>',
>             host: '<server>,
>             password: '<password>',
> 
>             // Display configuration
>             opacity: 0.4,
>             height: '100%',
>             imgChangeInterval: 10000,
> 
>             // FTP directory configuration
>             defaultDirPath: '</path/to/images>',
>             dirPathsAuthorized: ['</path/to/images>'],
>         },
>     },

Thank you for your time!

**Comment by jboucly** [comment]
Hi @Theofrastus 

Thanks for your reporting ! 
I thought I fixed this bug... 

Can you give me your arborescence of your directory ? For example : 

```
— dir1
—— img1
—— img2
—— img3
— dir2
—— img1
—— img1
—— dir3
——— img1
```

To solve this bug I would have to reproduce it locally.

**Comment by Theofrastus** [comment]
Thanks for reaching out!

I'll try to give as much info as I can (even potentially unnecessary info :D)

Both defaultDirPath and dirPathsAuthorized point to the same directory (although at first I didn't had dirPathsAuthorized specified, error appears with and without)
It's a single directory named "NameOfMySon-BestOf" (with a hyphen), containing 639 images.
The images have two naming conventions:

410 files named like this:
> 20240715_053355.jpg_compressed.JPEG

229 files names like this:
> IMG_20210907_205851.jpg_compressed.JPEG

So the dir tree would look like this:
> — NameOfMySon-BestOf
> —— 20240715_053355.jpg_compressed.JPEG (410 times)
> [...]
> —— IMG_20210907_205851.jpg_compressed.JPEG (229 times)

All images are jpegs, ranging in size from 145 kB to 1.2 MB, with only 20 images being larger than 1 MB.

The last image (alphabetically ascending), on which it stops has the name "IMG_20230607_145306.jpg_compressed.JPEG"

Please tell me if you need more information from me.

Thanks for your time, I really appreciate it!

Oh, and I just made sure, I'm on origin/main :)

**Comment by jboucly** [comment]
Thanks for all this information !

 I will try to find some time to solve this or find the problem in the coming month.

In case the bug is not solved in the time you would like, I encourage you to make a pull request proposal. 

I will keep you updated here 🤝

**Comment by jboucly** [comment]
@Theofrastus The fix is in the new release ! Let me know if this fix work for you in your magic mirror !

**Comment by Theofrastus** [comment]
Awesome! Thank you so much! I've let it run for a few hours and it didn't hang.

Thank you!
